# This is a basic workflow to help you get started with Actions

name: Prancer CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Runs a set of commands using the runners shell  
      - name: Install Prancer
        run: |
          pip3 install -U prancer-basic
          
      - name: Install opa and then run Prancer
        run: |
          curl -L -o /usr/local/bin/opa https://openpolicyagent.org/downloads/v0.36.1/opa_linux_amd64_static
          chmod 755 /usr/local/bin/opa
          # ls -l
          # curpwd=`pwd`
          # opaexe="$curpwd/opa"
          # echo "### opa listing ###"
          ls -l /usr/local/bin/opa
          echo "### opa version ###"
          /usr/local/bin/opa version
          echo "### pwd ###"
          pwd
          cd $curpwd
          pwd
          echo "#### path ###"
          export PATH=$PATH:$curpwd
          echo $PATH
          which opa
          echo "### helm ###"
          which helm
          # export APITOKEN=${{ secrets.APITOKEN }}
          # export GITTOKEN=${{ secrets.GITTOKEN }}
          # prancer --db REMOTE --env QA --company prancer-liquware armof

          
